### ISSUE TITLE
console里面提示什么就是有风险了？

### ISSUE THREAD

**Issue by Leng-bingo** [jokin1999/zhihuishu-web#1]
我看着看着就有一些红色的东西出来，不是视频的地址那个，会有什么影响吗

**Comment by Leng-bingo** [comment]
![tim 20181123204400](https://user-images.githubusercontent.com/44319750/48944194-b48f7700-ef60-11e8-95d3-4c0607cea910.png)

**Comment by josark2005** [comment]
没有影响，console没有提供风险预测的功能。
