### ISSUE TITLE
最简洁的代码奉上

### ISSUE THREAD

**Issue by xiaojie0202** [jokin1999/zhihuishu-web#2]

**Comment by xiaojie0202** [comment]
window.setInterval(function () { 
        if ($('.passTime').width() === 100 | $('.passTime').width() === 1477) {
            $('#nextBtn').click()
        }
        $('.popbtn_cancel').click();
        $('.speedTab15').click()
        
    }, 5000);

**Comment by josark2005** [comment]
除了没有静音外，确实理论上是减少了很多代码量。第一次生产的代码也就是差不多这几行，但是奈何会存在一些不可预知的错误......
